name: Publish NuGet Package # Action名称

# 设置触发器
# 以下示例为master分支，Directory.Build.props文件发生变动后，
# 触发本action
on:
  push:
    branches:
      - main # 监听的分支
    tags:
      - 'v*' # 监听的tag

# 设置运行环境及执行步骤
# 作用见step name
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Pack NuGet package
        run: |
          cd ErcJul.Tailwind
          dotnet pack ErcJul.Tailwind.csproj  --configuration Release -p:PackageVersion=${{ github.ref }}

      # 需在github库中设置${{ secrets.NUGET_API_KEY }}
      - name: Publish NuGet package
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate