name: Publish NuGet Package # Action名称

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore NuGet packages
        run: |
          cd ErcJul.Tailwind
          dotnet restore ErcJul.Tailwind.csproj
      
      - name: Get TailwindCli
        run: ./script/get_tailwind_cli.sh v4.1.11
      
      - name: Pack NuGet package
        run: |
          cd ErcJul.Tailwind
          dotnet pack ErcJul.Tailwind.csproj  --configuration Release -p:PackageVersion=${GITHUB_REF##*/v}

      - name: Publish NuGet package
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate